#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/sony/pdx234

PRODUCT_COPY_FILES += \
    vendor/sony/pdx234/proprietary/vendor/camera/CAMINO_FW_DATA_AF_0x0104.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CAMINO_FW_DATA_AF_0x0104.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/CAMINO_FW_DATA_OIS_0x0106.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CAMINO_FW_DATA_OIS_0x0106.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/CAMINO_FW_DATA_OIS_KAI_0x0102.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CAMINO_FW_DATA_OIS_KAI_0x0102.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/CAMINO_FW_DATA_OIS_KAI_0x0104.dat:$(TARGET_COPY_OUT_VENDOR)/camera/CAMINO_FW_DATA_OIS_KAI_0x0104.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/color_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/dataflow.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/draw_comp_histogram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/draw_comp_histogram.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/draw_comp_pocky.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/draw_comp_pocky.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/dual_bokeh_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/dual_bokeh_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/exposure_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/exposure_ctrl_diagram.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/eye_stabilizer.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/eye_stabilizer.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/face_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/face_detector_soda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/face_detector_soda.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/flicker_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/food_comp_yummy.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/hal_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/hal_ctrl_ife_lsc41.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/hal_ctrl_ife_lsc41.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/hdr_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/idt_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv_cheesescone.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv_marble.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv_raisin.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/image_conv_zunda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/image_conv_zunda.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/lens_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/lens_ctrl_common.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/motion_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/motion_detector_sumomo.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/motion_estimation.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/object_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/object_tracker.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/prc_image_conv.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/raw_conv_parisbrest.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/raw_conv_parisbrest.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/raw_proc_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/raw_proc_platform.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/recognize_map_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/recognize_map_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/LGI12BC0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/LGI12BC0/scene_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/MAUNAKEA_FW_DATA_1_0x16903000.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MAUNAKEA_FW_DATA_1_0x16903000.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/MAUNAKEA_FW_DATA_1_0x16903040.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MAUNAKEA_FW_DATA_1_0x16903040.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/MAUNAKEA_FW_DATA_2_0x16903000.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MAUNAKEA_FW_DATA_2_0x16903000.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/MAUNAKEA_FW_DATA_2_0x16903040.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MAUNAKEA_FW_DATA_2_0x16903040.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/MAUNAKEA_FW_DATA_4_0x16903000.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MAUNAKEA_FW_DATA_4_0x16903000.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/MAUNAKEA_FW_DATA_4_0x16903040.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MAUNAKEA_FW_DATA_4_0x16903040.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/MAUNAKEA_FW_DATA_5_0x16903000.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MAUNAKEA_FW_DATA_5_0x16903000.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/MAUNAKEA_FW_DATA_5_0x16903040.dat:$(TARGET_COPY_OUT_VENDOR)/camera/MAUNAKEA_FW_DATA_5_0x16903040.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/Morpho/CLBokeh/MorphoBokeh.bin.89ec02e:$(TARGET_COPY_OUT_VENDOR)/camera/Morpho/CLBokeh/MorphoBokeh.bin.89ec02e \
    vendor/sony/pdx234/proprietary/vendor/camera/Morpho/CLBokeh/MorphoFormatUtil.bin.347db6fd:$(TARGET_COPY_OUT_VENDOR)/camera/Morpho/CLBokeh/MorphoFormatUtil.bin.347db6fd \
    vendor/sony/pdx234/proprietary/vendor/camera/Morpho/Halide/halide_13831235:$(TARGET_COPY_OUT_VENDOR)/camera/Morpho/Halide/halide_13831235 \
    vendor/sony/pdx234/proprietary/vendor/camera/Morpho/Halide/halide_13849903:$(TARGET_COPY_OUT_VENDOR)/camera/Morpho/Halide/halide_13849903 \
    vendor/sony/pdx234/proprietary/vendor/camera/Morpho/Halide/halide_13896217:$(TARGET_COPY_OUT_VENDOR)/camera/Morpho/Halide/halide_13896217 \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/color_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/dataflow.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/draw_comp_histogram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/draw_comp_histogram.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/draw_comp_pocky.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/draw_comp_pocky.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/dual_bokeh_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/dual_bokeh_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/exposure_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/exposure_ctrl_diagram.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/eye_stabilizer.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/eye_stabilizer.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/face_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/face_detector_soda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/face_detector_soda.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/flicker_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/food_comp_yummy.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/hal_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/hal_ctrl_ife_lsc41.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/hal_ctrl_ife_lsc41.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/hdr_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/idt_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/image_conv.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/image_conv_cheesescone.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/image_conv_marble.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/image_conv_raisin.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/image_conv_zunda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/image_conv_zunda.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/lens_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/lens_ctrl_common.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/motion_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/motion_detector_sumomo.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/motion_estimation.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/object_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/object_tracker.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/prc_image_conv.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/raw_conv_parisbrest.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/raw_conv_parisbrest.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/raw_proc_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/raw_proc_platform.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/recognize_map_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/recognize_map_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM12BC9/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM12BC9/scene_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/color_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/dataflow.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/draw_comp_histogram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/draw_comp_histogram.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/draw_comp_pocky.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/draw_comp_pocky.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/dual_bokeh_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/dual_bokeh_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/exposure_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/exposure_ctrl_diagram.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/eye_stabilizer.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/eye_stabilizer.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/face_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/face_detector_soda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/face_detector_soda.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/flicker_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/food_comp_yummy.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/hal_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/hal_ctrl_ife_lsc41.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/hal_ctrl_ife_lsc41.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/hdr_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/idt_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/image_conv.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/image_conv_cheesescone.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/image_conv_marble.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/image_conv_raisin.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/image_conv_zunda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/image_conv_zunda.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/lens_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/lens_ctrl_common.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/motion_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/motion_detector_sumomo.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/motion_estimation.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/object_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/object_tracker.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/prc_image_conv.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/raw_conv_parisbrest.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/raw_conv_parisbrest.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/raw_proc_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/raw_proc_platform.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/recognize_map_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/recognize_map_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SEM52BC0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SEM52BC0/scene_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SODA_HMN_BN0010-0001:$(TARGET_COPY_OUT_VENDOR)/camera/SODA_HMN_BN0010-0001 \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/color_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/color_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/dataflow.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/dataflow.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/draw_comp_histogram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/draw_comp_histogram.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/draw_comp_pocky.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/draw_comp_pocky.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/dual_bokeh_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/dual_bokeh_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/exposure_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/exposure_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/exposure_ctrl_diagram.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/exposure_ctrl_diagram.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/eye_stabilizer.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/eye_stabilizer.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/face_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/face_detector_soda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/face_detector_soda.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/flicker_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/flicker_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/food_comp_yummy.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/food_comp_yummy.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/hal_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/hal_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/hal_ctrl_ife_lsc41.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/hal_ctrl_ife_lsc41.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/hdr_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/hdr_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/idt_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/idt_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/image_conv.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/image_conv_cheesescone.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/image_conv_cheesescone.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/image_conv_marble.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/image_conv_marble.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/image_conv_raisin.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/image_conv_raisin.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/image_conv_zunda.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/image_conv_zunda.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/lens_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/lens_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/lens_ctrl_common.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/lens_ctrl_common.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/motion_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/motion_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/motion_detector_sumomo.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/motion_detector_sumomo.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/motion_estimation.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/motion_estimation.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/object_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/object_tracker.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/object_tracker.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/prc_image_conv.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/prc_image_conv.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/raw_conv_parisbrest.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/raw_conv_parisbrest.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/raw_proc_platform.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/raw_proc_platform.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/recognize_map_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/recognize_map_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/SUN12BS0/scene_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/SUN12BS0/scene_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/default.dat:$(TARGET_COPY_OUT_VENDOR)/camera/default.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/display_ctrl.dat:$(TARGET_COPY_OUT_VENDOR)/camera/display_ctrl.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_animal_eye_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_animal_eye_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_autoexposure.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_autoexposure.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_autowhitebalance_00.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_autowhitebalance_00.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_face_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_face_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_object_detector.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_object_detector.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_recognize_map_comp.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_recognize_map_comp.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_00.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_00.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_01.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_01.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_02.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_02.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_03.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_03.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_04.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_04.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_05.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_05.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_06.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_06.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_07.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_07.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_08.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_08.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_09.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_09.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_10.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_10.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_11.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_11.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_12.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_12.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_13.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_13.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_14.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_14.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_15.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_15.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_16.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_16.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_17.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_17.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_18.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_18.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_19.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_19.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_20.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_20.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_21.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_21.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_22.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_22.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/file_zunda_23.dat:$(TARGET_COPY_OUT_VENDOR)/camera/file_zunda_23.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/flash.dat:$(TARGET_COPY_OUT_VENDOR)/camera/flash.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/ois_correction_coefficient_imx650.dat:$(TARGET_COPY_OUT_VENDOR)/camera/ois_correction_coefficient_imx650.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/ois_correction_coefficient_imx888.dat:$(TARGET_COPY_OUT_VENDOR)/camera/ois_correction_coefficient_imx888.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/optical_axis.dat:$(TARGET_COPY_OUT_VENDOR)/camera/optical_axis.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/snapshot.dat:$(TARGET_COPY_OUT_VENDOR)/camera/snapshot.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/streaming.dat:$(TARGET_COPY_OUT_VENDOR)/camera/streaming.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/supported.dat:$(TARGET_COPY_OUT_VENDOR)/camera/supported.dat \
    vendor/sony/pdx234/proprietary/vendor/camera/version.dat:$(TARGET_COPY_OUT_VENDOR)/camera/version.dat \
    vendor/sony/pdx234/proprietary/vendor/etc/acdbdata/kalama_qrd/Sony_acdb_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kalama_qrd/Sony_acdb_cal.acdb \
    vendor/sony/pdx234/proprietary/vendor/etc/acdbdata/kalama_qrd/Sony_workspaceFileXml.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/kalama_qrd/Sony_workspaceFileXml.qwsp \
    vendor/sony/pdx234/proprietary/vendor/etc/camera/camxoverridesettings.txt:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camxoverridesettings.txt \
    vendor/sony/pdx234/proprietary/vendor/etc/display/qdcm_calib_data_1.json:$(TARGET_COPY_OUT_VENDOR)/etc/display/qdcm_calib_data_1.json \
    vendor/sony/pdx234/proprietary/vendor/etc/displayconfig/display_id_131.xml:$(TARGET_COPY_OUT_VENDOR)/etc/displayconfig/display_id_131.xml \
    vendor/sony/pdx234/proprietary/vendor/etc/init/vendor.somc.hardware.camera.provider@1.0-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.somc.hardware.camera.provider@1.0-service.rc \
    vendor/sony/pdx234/proprietary/vendor/etc/libhdr_somc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/libhdr_somc.xml \
    vendor/sony/pdx234/proprietary/vendor/etc/libnfc-nci.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nci.conf \
    vendor/sony/pdx234/proprietary/vendor/etc/libnfc-nxp.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp.conf \
    vendor/sony/pdx234/proprietary/vendor/etc/libnfc-nxp_RF.conf:$(TARGET_COPY_OUT_VENDOR)/etc/libnfc-nxp_RF.conf \
    vendor/sony/pdx234/proprietary/vendor/etc/wifi/bdwlan.e17:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan.e17 \
    vendor/sony/pdx234/proprietary/vendor/etc/wifi/bdwlan.e30:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan.e30 \
    vendor/sony/pdx234/proprietary/vendor/etc/wifi/bdwlan.e31:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/bdwlan.e31 \
    vendor/sony/pdx234/proprietary/vendor/etc/wifi/regdb.bin:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/regdb.bin \
    vendor/sony/pdx234/proprietary/vendor/etc/wifi/wifi_txpower.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wifi_txpower.conf \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_mono_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_Front_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Front_mono_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_mono_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_Logical_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_Logical_mono_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_mono_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Tele_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Tele_mono_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_mono_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_UWide_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_UWide_mono_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_mono_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_mono_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_P_Wide_mono_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_P_Wide_mono_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_default_44k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_default_44k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_default_48k.tbl:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_default_48k.tbl \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_parameter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_parameter.xml \
    vendor/sony/pdx234/proprietary/vendor/etc/zoom_noise_reduction/znr_parameter_back.xml:$(TARGET_COPY_OUT_VENDOR)/etc/zoom_noise_reduction/znr_parameter_back.xml \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b00 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b01 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b02 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b03 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b04 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b05 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b06 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b07 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b08 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b09 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b10 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b11 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b12 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b13 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b14 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b15 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b16 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b17 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b18 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b19 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.b20:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.b20 \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.elf \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mbn \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP.mdt \
    vendor/sony/pdx234/proprietary/vendor/firmware/CAMERA_ICP_170.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/CAMERA_ICP_170.elf \
    vendor/sony/pdx234/proprietary/vendor/firmware/L-cs35l45-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/L-cs35l45-dsp1-spk-cali.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/L-cs35l45-dsp1-spk-cali.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/L-cs35l45-dsp1-spk-cali.wmfw \
    vendor/sony/pdx234/proprietary/vendor/firmware/L-cs35l45-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/L-cs35l45-dsp1-spk-prot.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/L-cs35l45-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/L-cs35l45-dsp1-spk-prot.wmfw \
    vendor/sony/pdx234/proprietary/vendor/firmware/R-cs35l45-dsp1-spk-cali.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l45-dsp1-spk-cali.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/R-cs35l45-dsp1-spk-cali.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l45-dsp1-spk-cali.wmfw \
    vendor/sony/pdx234/proprietary/vendor/firmware/R-cs35l45-dsp1-spk-prot.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l45-dsp1-spk-prot.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/R-cs35l45-dsp1-spk-prot.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/R-cs35l45-dsp1-spk-prot.wmfw \
    vendor/sony/pdx234/proprietary/vendor/firmware/a740_sqe.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_sqe.fw \
    vendor/sony/pdx234/proprietary/vendor/firmware/a740_zap.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.b00 \
    vendor/sony/pdx234/proprietary/vendor/firmware/a740_zap.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.b01 \
    vendor/sony/pdx234/proprietary/vendor/firmware/a740_zap.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.b02 \
    vendor/sony/pdx234/proprietary/vendor/firmware/a740_zap.elf:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.elf \
    vendor/sony/pdx234/proprietary/vendor/firmware/a740_zap.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.mbn \
    vendor/sony/pdx234/proprietary/vendor/firmware/a740_zap.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/a740_zap.mdt \
    vendor/sony/pdx234/proprietary/vendor/firmware/cs40l20.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l20.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/cs40l25a_a2h.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_a2h.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/cs40l25a_a2h.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_a2h.wmfw \
    vendor/sony/pdx234/proprietary/vendor/firmware/cs40l25a_a2h1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_a2h1.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/cs40l25a_a2h2.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_a2h2.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/cs40l25a_a2h3.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_a2h3.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/cs40l25a_cal.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_cal.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/cs40l25a_cal.wmfw:$(TARGET_COPY_OUT_VENDOR)/firmware/cs40l25a_cal.wmfw \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b00:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b00 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b01:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b01 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b02:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b02 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b03:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b03 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b04:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b04 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b05:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b05 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b06:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b06 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b07:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b07 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b08:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b08 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b09:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b09 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b10:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b10 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b11:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b11 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b12:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b12 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b13:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b13 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b14:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b14 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b15:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b15 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b16:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b16 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b17:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b17 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b18:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b18 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.b19:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.b19 \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mbn \
    vendor/sony/pdx234/proprietary/vendor/firmware/evass.mdt:$(TARGET_COPY_OUT_VENDOR)/firmware/evass.mdt \
    vendor/sony/pdx234/proprietary/vendor/firmware/gmu_gen70200.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/gmu_gen70200.bin \
    vendor/sony/pdx234/proprietary/vendor/firmware/touch_module_id_0x01.img:$(TARGET_COPY_OUT_VENDOR)/firmware/touch_module_id_0x01.img \
    vendor/sony/pdx234/proprietary/vendor/firmware/vpu20_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v.mbn \
    vendor/sony/pdx234/proprietary/vendor/firmware/vpu20_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu20_4v_unsigned.mbn \
    vendor/sony/pdx234/proprietary/vendor/firmware/vpu30_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_4v.mbn \
    vendor/sony/pdx234/proprietary/vendor/firmware/vpu30_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu30_4v_unsigned.mbn \
    vendor/sony/pdx234/proprietary/vendor/firmware/vpu33_4v.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v.mbn \
    vendor/sony/pdx234/proprietary/vendor/firmware/vpu33_4v_unsigned.mbn:$(TARGET_COPY_OUT_VENDOR)/firmware/vpu33_4v_unsigned.mbn \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/com.qti.tuned.default.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.qti.tuned.default.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/com.sony.sensormodule.camino_imx650.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.sensormodule.camino_imx650.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/com.sony.sensormodule.crocus_imx663.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.sensormodule.crocus_imx663.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/com.sony.sensormodule.maunakea_imx563.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.sensormodule.maunakea_imx563.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/com.sony.sensormodule.maunakea_imx888.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.sensormodule.maunakea_imx888.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/com.sony.tuned.camino_imx650.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.tuned.camino_imx650.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/com.sony.tuned.crocus_imx663.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.tuned.crocus_imx663.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/com.sony.tuned.maunakea_imx563.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.tuned.maunakea_imx563.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/com.sony.tuned.maunakea_imx888.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/com.sony.tuned.maunakea_imx888.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/fdconfigpreview.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreview.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/fdconfigpreviewlite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigpreviewlite.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/fdconfigsecure.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigsecure.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/fdconfigvideo.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideo.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/fdconfigvideolite.bin:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/fdconfigvideolite.bin \
    vendor/sony/pdx234/proprietary/vendor/lib64/camera/imx688.pb:$(TARGET_COPY_OUT_VENDOR)/lib64/camera/imx688.pb

PRODUCT_PACKAGES += \
    libQnnHtp.cameraqnn \
    libQnnHtpV73Stub.cameraqnn \
    com.qti.eeprom.gt24p128c2csli_imx766 \
    com.qti.eeprom.gt24p64b_imx688 \
    com.qti.eeprom.irs2381c_polar \
    com.qti.eeprom.truly_cmb433 \
    com.qti.ois.bu63169gwz \
    com.qti.sensor.imx318 \
    com.qti.sensor.imx334 \
    com.qti.sensor.imx362 \
    com.qti.sensor.imx363 \
    com.qti.sensor.imx376 \
    com.qti.sensor.imx386 \
    com.qti.sensor.imx476 \
    com.qti.sensor.imx481 \
    com.qti.sensor.imx519 \
    com.qti.sensor.imx563 \
    com.qti.sensor.imx576 \
    com.qti.sensor.imx577 \
    com.qti.sensor.imx586 \
    com.qti.sensor.imx588 \
    com.qti.sensor.imx686 \
    com.qti.sensor.imx688 \
    com.qti.sensor.imx766 \
    com.qti.sensor.max7366_6dof \
    com.qti.sensor.max7366_eyetrack \
    com.qti.sensor.max7366_ov6211 \
    com.qti.sensor.max7366_ov9282 \
    com.qti.sensor.ov12a10 \
    com.qti.sensor.ov12a10_front \
    com.qti.sensor.ov13855 \
    com.qti.sensor.ov13880 \
    com.qti.sensor.ov64b40 \
    com.qti.sensor.ov7251 \
    com.qti.sensor.ov8856 \
    com.qti.sensor.ov8856_master \
    com.qti.sensor.ov8856_slave \
    com.qti.sensor.s5k2l7 \
    com.qti.sensor.s5k2x5sp \
    com.qti.sensor.s5k33dxx \
    com.qti.sensor.s5k3m5 \
    com.qti.sensor.s5k3p9 \
    com.qti.sensor.s5k4h7 \
    com.qti.sensor.s5k5e9yu05 \
    com.qti.sensor.s5k5e9yx04 \
    com.qti.sensor.s5khp1s \
    com.qti.sensor.s5kjd1sp \
    com.bots.node.vendortagwrite \
    com.qti.eisv2 \
    com.qti.eisv3 \
    com.qti.hvx.addconstant \
    com.qti.hvx.binning \
    com.qti.node.afbfusion \
    com.qti.node.aon \
    com.qti.node.customhwnode \
    com.qti.node.depth \
    com.qti.node.depthprovider \
    com.qti.node.dewarp \
    com.qti.node.dummydepth \
    com.qti.node.dummyrtb \
    com.qti.node.dummysat \
    com.qti.node.eisv2 \
    com.qti.node.eisv3 \
    com.qti.node.fcv \
    com.qti.node.formatconversion \
    com.qti.node.gme \
    com.qti.node.gpu \
    com.qti.node.gyrornn \
    com.qti.node.hdr10pgen \
    com.qti.node.hdr10phist \
    com.qti.node.memcpy \
    com.qti.node.ml \
    com.qti.node.muxer \
    com.qti.node.remosaic \
    com.qti.node.seg \
    com.qti.node.stich \
    com.qti.node.swaidenoiser \
    com.qti.node.swbestats \
    com.qti.node.swcac \
    com.qti.node.swec \
    com.qti.node.swfusion \
    com.qti.node.swhme \
    com.qti.node.swlsc \
    com.qti.node.swmctf \
    com.qti.node.swpdpc \
    com.qti.node.swpreprocess \
    com.qti.node.swregistration \
    com.qti.node.swvrt \
    com.qti.stats.aec \
    com.qti.stats.aecwrapper \
    com.qti.stats.aecxcore \
    com.qti.stats.af \
    com.qti.stats.afd \
    com.qti.stats.afwrapper \
    com.qti.stats.asd \
    com.qti.stats.awb \
    com.qti.stats.awbwrapper \
    com.qti.stats.cnndriver \
    com.qti.stats.haf \
    com.qti.stats.hafoverride \
    com.qti.stats.localhistogram \
    com.qti.stats.pdlib \
    com.qti.stats.pdlibsony \
    com.qti.stats.pdlibwrapper \
    com.qti.stats.statsgenerator \
    com.qti.stats.tracker \
    com.qtistatic.stats.aec \
    com.qtistatic.stats.af \
    com.qtistatic.stats.awb \
    com.qtistatic.stats.pdlib \
    libdepthmapwrapper \
    libdepthmapwrapper_secure \
    libexcal_ckb_service_plugin \
    libexcal_color_ctrl_plugin \
    libexcal_debug_display_plugin \
    libexcal_draw_comp_plugin \
    libexcal_dual_bokeh_comp_plugin \
    libexcal_exposure_analyzer_plugin \
    libexcal_exposure_ctrl_plugin \
    libexcal_eye_stabilizer_plugin \
    libexcal_face_detector_plugin \
    libexcal_flicker_detector_plugin \
    libexcal_food_comp_plugin \
    libexcal_hal_ctrl_plugin \
    libexcal_hdr_plugin \
    libexcal_idt_ctrl_plugin \
    libexcal_image_conv_plugin \
    libexcal_iq_ctrl_plugin \
    libexcal_jpeg_enc_plugin \
    libexcal_lens_ctrl_plugin \
    libexcal_motion_detector_plugin \
    libexcal_motion_estimation_plugin \
    libexcal_object_detector_plugin \
    libexcal_object_tracker_plugin \
    libexcal_offline_process_ctrl_plugin \
    libexcal_prc_image_conv_plugin \
    libexcal_raw_conv_plugin \
    libexcal_raw_dump_plugin \
    libexcal_raw_proc_plugin \
    libexcal_recognize_map_comp_plugin \
    libexcal_req_ctrl_plugin \
    libexcal_scene_detector_plugin \
    libexcal_single_bokeh_comp_plugin \
    libexcal_snapshot_ctrl_plugin \
    libexcal_splitter_plugin \
    libexcal_stream_ctrl_plugin \
    camx.device-impl \
    camx.provider-impl \
    com.qti.camx.chiiqutils \
    com.qti.chiusecaseselector \
    com.qti.feature2.afbrckt \
    com.qti.feature2.anchorsync \
    com.qti.feature2.demux \
    com.qti.feature2.derivedoffline \
    com.qti.feature2.frameselect \
    com.qti.feature2.fusion \
    com.qti.feature2.generic \
    com.qti.feature2.gs.sm8550 \
    com.qti.feature2.hdr \
    com.qti.feature2.mcreprocrt \
    com.qti.feature2.memcpy \
    com.qti.feature2.mfsr \
    com.qti.feature2.ml \
    com.qti.feature2.mux \
    com.qti.feature2.qcfa \
    com.qti.feature2.rawhdr \
    com.qti.feature2.realtimeserializer \
    com.qti.feature2.rt \
    com.qti.feature2.rtmcx \
    com.qti.feature2.serializer \
    com.qti.feature2.statsregeneration \
    com.qti.feature2.stub \
    com.qti.feature2.swmf \
    com.qti.qseeaon \
    com.qti.qseeutils \
    com.qti.settings.sm8550 \
    com.qti.stats.common \
    com.qualcomm.mcx.distortionmapper \
    com.qualcomm.mcx.linearmapper \
    com.qualcomm.mcx.nonlinearmapper \
    com.qualcomm.mcx.policy.mfl \
    com.qualcomm.mcx.policy.xr \
    com.qualcomm.qti.mcx.usecase.extension \
    camera.qcom \
    com.qti.chi.offline \
    com.qti.chi.override \
    libSnpeHtpPrepare \
    libaidenoiser \
    libaidenoiserv2 \
    libarcsoft_bokeh_adapter \
    libarcsoft_dualcam_refocus_image \
    libarcsoft_dualcam_refocus_video \
    libarcsoft_hdr_adapter \
    libarcsoft_high_dynamic_range_v5 \
    libarcsoft_low_light_hdr \
    libarcsoft_qnnhtp \
    libbitmlengine \
    libbitmlenginev2 \
    libcamerapostproc \
    libcammw \
    libcammw_util \
    libcamxcommonutils \
    libcamxexternalformatutils \
    libcamxfacialfeatures \
    libcamxfdalgo \
    libcamxfdengine \
    libcamxhwnodecontext \
    libcamxifestriping \
    libcamximageformatutils \
    libcamxqsatalgo \
    libcamxsettingsmanager \
    libcamxstatscore \
    libcamxswispiqmodule \
    libcamxswprocessalgo \
    libcamxtintlessalgo \
    libchifeature2 \
    libchilog \
    libcom.qti.chinodeutils \
    libcommonchiutils \
    libdepthcomputation \
    libexcal_core \
    libexcal_system \
    libhdr10plus \
    libhdr_stub \
    libipebpsstriping \
    libipebpsstriping170 \
    libipebpsstriping480 \
    libisphwsetting \
    libjpege \
    libmctfengine_stub \
    libmfGhostDetection \
    libmfec \
    libmmcamera_bestats \
    libmmcamera_cac3 \
    libmmcamera_lscv35 \
    libmmcamera_mfnr \
    libmmcamera_mfnr_t4 \
    libmmcamera_pdpc \
    libmorpho_single_camera \
    libmpbase \
    libnanopb \
    libopencv \
    libopencv3a \
    libopestriping \
    libos \
    libqll \
    libqll10 \
    libqllengine \
    libqsegnet \
    libqshcamera \
    libsfeShiftExtrapolation \
    libsomc_aerial \
    libsomc_alfortlpserv \
    libsomc_angelpie \
    libsomc_baran \
    libsomc_buttercake \
    libsomc_buttercakersc \
    libsomc_camerahal \
    libsomc_camerapal \
    libsomc_cheesescone \
    libsomc_cheesesconersc \
    libsomc_chokoballcmn \
    libsomc_chokoballkeymgr \
    libsomc_chokoballpal \
    libsomc_cornfrosty \
    libsomc_donutscmnserv \
    libsomc_drops \
    libsomc_dropsrsc \
    libsomc_facewrapper \
    libsomc_flicker \
    libsomc_formatconverter \
    libsomc_formatconverterrsc \
    libsomc_histogram \
    libsomc_histogramrsc \
    libsomc_madeleinebase \
    libsomc_marble \
    libsomc_marblersc \
    libsomc_oshirukoserv \
    libsomc_parisbrest \
    libsomc_parisbrestrsc \
    libsomc_pdnserv \
    libsomc_pocky \
    libsomc_pockyrsc \
    libsomc_pretzchoco \
    libsomc_pretzchocorsc \
    libsomc_raisincl \
    libsomc_raisinclrsc \
    libsomc_sheera \
    libsomc_shortcake \
    libsomc_shortcakersc \
    libsomc_soda \
    libsomc_sukonbu \
    libsomc_sumomo \
    libsomc_sumomorsc \
    libsomc_thermal \
    libsomc_wasabeef \
    libsomc_yummy \
    libsomc_yummyrsc \
    libsomc_zunda \
    libsony_animaleye \
    libsony_asr \
    libsony_cc \
    libsony_ec \
    libsony_facestab \
    libsony_fc \
    libsony_naruto \
    libsony_stab \
    libspectre \
    libswregistrationalgo \
    libsynx \
    libtfestriping \
    libthreadutils \
    libubifocus \
    libvideoml \
    local_libcamera_metadata \
    vendor.qti.hardware.camera.aon-service-impl \
    vendor.qti.hardware.camera.postproc@1.0-service-impl \
    vendor.somc.camera.device-impl \
    vendor.somc.hardware.camera.provider.manifest.xml \
    vendor.somc.hardware.camera.provider@1.0-service

PRODUCT_PACKAGES += \
    vendor_firmware_kiwi_bdwlan_e17 \
    vendor_firmware_kiwi_bdwlan_e30 \
    vendor_firmware_kiwi_bdwlan_e31 \
    vendor_firmware_kiwi_regdb_bin
